image: arnobirchler/gitlab-ci:7.2

stages:
  - build
  - services
  - test

composer:
  stage: build
  script:
    - composer install --dev
    - composer post-root-package-install
    - composer post-create-project-cmd
    
artisan :
  stage: services
  script:
    - nohup php artisan serv &

acceptance:
  stage: test
  script:
    - php ./vendor/bin/codecept run acceptance

unit:
  stage: test
  script:
    - composer unit-test
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

