image: arnobirchler/gitlab-ci:7.2

cache:
  paths:
    - vendor/
    - node_modules/

stages:
  - build
  - test


job 1:
  stage: build
  script:
    - composer install

job 2:
  stage: test
  script:
    - php vendor/bin/codecept run acceptance

job 3:
  stage: test
  script:
    - php vendor/bin/codecept run functional

job 4:
  stage: test
  script:
    - php vendor/bin/codecept run unit --coverage
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

