image: arnobirchler/gitlab-ci:7.2

stages:
  - build
  - services
  - test

composer:
  stage: build
  script:
    - composer install --dev
    - php artisan key:generate

artisan :
  stage: services
  script:
    - nohup php artisan serv &

acceptance:
  stage: test
  script:
    - composer acceptance-test

unit:
  stage: test
  script:
    - composer unit-test
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

