image: arnobirchler/gitlab-ci:7.2

cache:
  paths:
    - vendor/
    - node_modules/

stages:
  - build
  - services
  - test


composer:
  stage: build
  script:
    - composer install --dev

start-server:
  stage: services
  script:
    - composer artisan serv
  dependencies:
    - composer

acceptance:
  stage: test
  script:
    - composer acceptance-test

functional:
  stage: test
  script:
    - composer functional-test

unit:
  stage: test
  script:
    - composer unit-test
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

