image: arnobirchler/gitlab-ci:7.2

stages:
  - build
  - test

composer:
  stage: build
  script:
    - composer install --dev
    - cp .env.example .env
    - php artisan key:generate
    - nohup php artisan serv &

acceptance:
  stage: test
  script:
    - php ./vendor/bin/codecept run acceptance

unit:
  stage: test
  script:
    - composer unit-test
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

