image: arnobirchler/gitlab-ci:7.2

cache:
  paths:
    - vendor/
    - node_modules/

stages:
  - build
  - test


composer:
  stage: build
  script:
    - composer install --dev

acceptance:
  stage: test
  script:
    - composer acceptance-test

unit:
  stage: test
  script:
    - composer unit-test
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

